CCCHH: Use new endpoint
SpaceApi/directory pull request #247
Opened 2024-01-16 01:04 UTC by julianschacher

We have a new endpoint now. The old one will still work for the foreseeable future, but yeah, let's use the new one here.

2024-01-16 23:40 UTC, s3lph requested changes
Hi @julianschacher 

Thanks for the update. Unfortunately, your new endpoint does currently not pass schema validation. The units of your temperature sensors [should be `°C`](https://spaceapi.io/docs/#schema-key-sensors-temperature-unit), not `C`. You can check the validity yourself in our validator tool: https://validator.spaceapi.io/ui/?url=https://spaceapi.hamburg.ccc.de/.

Once that's fixed, we'll gladly merge your PR.

2024-01-20 17:16 UTC, rnestler commented
@julianschacher Could you fix your endpoint?

2024-01-21 02:48 UTC, julianschacher commented
Endpoint fixed, thanks for pointing out the problem!

2024-01-21 03:45 UTC, s3lph approved these changes
Thanks for the fix, LGTM now.

2024-01-21 03:45 UTC, merged