changed the Endpoint from Odenwilusenz
SpaceApi/directory pull request #248
Opened 2024-01-17 18:51 UTC by Elija-K

2024-01-17 21:25 UTC, dbrgn commented
Der Validator meldet aktuell noch Fehler: https://validator.spaceapi.io/ui/?url=http://spaceapi.odenwilusenz.ch/api.json

Und: Habt ihr auch HTTPS für den Endpoint? Das wäre natürlich besser als nur HTTP. (Aber es ist kein Requirement für das Directory.)

2024-01-17 22:00 UTC, Elija-K commented
Nein leider noch nicht wird aber auch bald gemacht wenn das so der Wunsch ist!

-------- Original-Nachricht --------
Am 17. Jan. 2024, 22:25, schrieb Danilo Bargen :

> Der Validator meldet aktuell noch Fehler: https://validator.spaceapi.io/ui/?url=http://spaceapi.odenwilusenz.ch/api.json
>
> Und: Habt ihr auch HTTPS für den Endpoint? Das wäre natürlich besser als nur HTTP. (Aber es ist kein Requirement für das Directory.)
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/SpaceApi/directory/pull/248#issuecomment-1896805928), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BBZWE6O7LMPRKWVMOKX4LIDYPA6WNAVCNFSM6AAAAABB7BCNU2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJWHAYDKOJSHA).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-01-18 08:42 UTC, rnestler requested changes

2024-01-18 08:42 UTC, rnestler commented on directory.json
> +  "Odenwilusenz": "spaceapi.odenwilusenz.ch/api.json",
Can you include either `http://` or `https://` in the URL? I'm not even sure if it would work like this.

2024-01-18 08:57 UTC, Elija-K commented
i think it would not work, until i change it on github but we can try, its not a big thing vecause we are not finished yet with the API

-------- Original-Nachricht --------
Am 18. Jan. 2024, 09:42, schrieb Raphael Nestler :

> @rnestler requested changes on this pull request.
>
> ---------------------------------------------------------------
>
> In [directory.json](https://github.com/SpaceApi/directory/pull/248#discussion_r1457103713):
>
>> @@ -139,6 +139,7 @@
>    "Noklab": "https://cccgoe.de/spaceapi.php",
>    "Nottinghack": "https://hms.nottinghack.org.uk/api/spaceapi ",
>    "Nova Labs": "http://nova-labs.org/api/",
> +  "Odenwilusenz": "spaceapi.odenwilusenz.ch/api.json",
>
> Can you include either http:// or https:// in the URL? I'm not even sure if it would work like this.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/SpaceApi/directory/pull/248#pullrequestreview-1829140926), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BBZWE6MZEMXY7BDBTS5J6V3YPDN7RAVCNFSM6AAAAABB7BCNU2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMRZGE2DAOJSGY).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-01-18 21:15 UTC, Elija-K commented
i did it now and i hope its ok!!

2024-01-18 21:49 UTC, dbrgn approved these changes
Perfect, thanks!

I will resolve the conflict and push directly to your branch, and will then merge.

2024-01-18 21:51 UTC, dbrgn approved these changes

2024-01-18 21:51 UTC, merged

2024-05-04 22:03 UTC, dbrgn commented
@Elija-K cool dass ihr inzwischen weitere keys hinzugefügt habt! leider gibt es momentan wieder diverse validierungs-probleme: https://validator.spaceapi.io/ui/?url=https://spaceapi.odenwilusenz.ch/api.json

2024-05-07 11:23 UTC, Elija-K commented
Hallo @dbrgn, wir waren mal dran das zu fixen, kamen aber auf keine Lösung da jedes JavaScript validator gesagt hat, ist korrekt aber der Spaceapi validator gesagt hat es stimmt was nicht, wir wollten mal abwarten, jedoch probieren wir es wieder, ich werde das Morgen im Team besprechen!

MfG
Elija-K

2024-05-07 13:48 UTC, rnestler commented
@Elija-K Die Fehler sind relativ einfach zu fixen:

 * `projects` muss ein array sein, also: `["https://github.com/odenwilusenz"]`
 * `sensors.network_traffic[0].properties.maximum` muss eine Zahl sein, also: `"maximum": 0,` oder einfach weglassen
 * `sensors.temperature.unit` muss `°C` sein anstatt nur `C`